### ISSUE TITLE
Подстроить ширины

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#10]
Лин
![macr](https://cloud.githubusercontent.com/assets/4154978/11898976/f283d5fc-a5ac-11e5-827a-979d34dcddda.png)

**Comment by kvichans** [comment]
Да, нужно оставлять с запасом.

Еще мне полезно было бы увидеть как расположен текст в edit. Дайте снимок

**Comment by Alexey-T** [comment]
по центру Едит. и все.

**Comment by kvichans** [comment]
"по центру"? Это мне ни о чем не говорит. Важно: текст в label и в edit на одном уровне?

**Comment by Alexey-T** [comment]
на одной ОС бужет на одном. на другой нет
делайте лабел по верху едит +0...2 пкс

**Comment by kvichans** [comment]
Уже делаю +3

**Comment by Alexey-T** [comment]
хор.
так что не "важно"
