### ISSUE TITLE
btn caption

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#14]
Export macros:
"ncheck a"-OSX обрезает ткс 
(хочет показать пустое место, на крае)

**Comment by kvichans** [comment]
что было? что стало?

**Comment by kvichans** [comment]
почему тема называется "btn caption"?

**Comment by Alexey-T** [comment]
кнопа:Uncheck all
osx показывает:nheck a
Места мало

**Comment by kvichans** [comment]
А-а. Расширю
