### ISSUE TITLE
Er on start 

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#16]
Вместе с плагином ConfMenu (его только ставлю)
показывает ошибку при старте

```
Python 3.4.3
OK config menus from "/home/user/cuda/cuda/app/settings/menu.json"
Loading icons: LibreOffice_24x24
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_macros/cd_macros.py", line 72, in on_start
    self._do_acts(acts='|reg|menu|')
  File "/home/user/cuda/cuda/app/py/cuda_macros/cd_macros.py", line 611, in _do_acts
    self.adapt_menu()
  File "/home/user/cuda/cuda/app/py/cuda_macros/cd_macros.py", line 96, in adapt_menu
    plg_ind = [i for (i,nm) in enumerate(top_nms) if '|plugins' in nm][0]
IndexError: list index out of range
```

**Comment by Alexey-T** [comment]
Config
[macros.zip](https://github.com/kvichans/cuda_macros/files/924538/macros.zip)
[menu.zip](https://github.com/kvichans/cuda_macros/files/924540/menu.zip)

**Comment by kvichans** [comment]
Повторил

**Comment by kvichans** [comment]
Проблема в ядре Куд.
Вот способ ее воспроизвести
1. Заполнить menu.json так
```json
[
  {"cap":"", "hint":"top", "sub": [
      {"cap":"&Plugins", "hint":"plugins"}
     ,{"cap":"&Tools", "hint":"_cuda_exttools:adapt_menu"}
  ]}
]
```
2. Вызвать конфигуратор меню, применить этот файл.
3. В консоли вызывать `=app_proc(PROC_MENU_ENUM, 'top')`
У меня выдает ответ
`&Plugins||18612336`
`&Tools|_cuda_exttools:adapt_menu|18619376`
4. В этом ответе ошибка - для Plugins нет cmd. В нормальном состоянии отдает так `&Plugins|plugins|18612336`

Более того, у меня после такого конфигурирования меню Куд дуреет - лезут ошибки "с памятью" при переходах между табами и при открытии файлов.

**Comment by Alexey-T** [comment]
Непонятно в чем ошибка куд. Может плаг сделал не верное меню

**Comment by kvichans** [comment]
У вас есть повтор?

**Comment by Alexey-T** [comment]
Если повторить без плага можно то лучше.

**Comment by Alexey-T** [comment]
Смотрю

**Comment by Alexey-T** [comment]
Да, повторил ответ в консоли
(если повторить без плага, лучше)

**Comment by kvichans** [comment]
Пробую..

**Comment by Alexey-T** [comment]
может баг в ядре- но как повторить.

**Comment by kvichans** [comment]
Последовательность вызовов из конфигуратор-плагина, которую можно вызвать в консоли
```python
app_proc(PROC_MENU_CLEAR, 'top')
app_proc(PROC_MENU_ADD, 'top;plugins;&Plugins')
```
После этого `=app_proc(PROC_MENU_ENUM, 'top')` дает неверный ответ

**Comment by Alexey-T** [comment]
Ok, смотрю

**Comment by Alexey-T** [comment]
правка. Теперь ответ апи нормальный.

**Comment by kvichans** [comment]
Сразу попробуйте на своих 
macros.json
menu.json

**Comment by Alexey-T** [comment]
Попробовал- пока нет этой ош.

**Comment by kvichans** [comment]
Есть идеи, почему память портилась?

**Comment by Alexey-T** [comment]
нет..

**Comment by kvichans** [comment]
тогда жду бету, для проверки что у меня память теперь не портится

**Comment by Alexey-T** [comment]
beta http://uvviewsoft.com/bb/cudatext-win-x64-1.8.1.0.zip

**Comment by kvichans** [comment]
Проблема с памятью осталась. 
Стабильно повторяется:
- Запуск Куд
- Применение 
```json
[
  {"cap":"", "hint":"top", "sub": [
      {"cap":"&Plugins", "hint":"plugins"}
  ]}
]
```
- Открытие второго файла из ТС дает сообщение ОС "Прекращена работа программы"

**Comment by kvichans** [comment]
Проблемы начинаются после
`app_proc(PROC_MENU_CLEAR, 'top')`
`app_proc(PROC_MENU_ADD, 'top;plugins;&Plugins')`

**Comment by Alexey-T** [comment]
Лучше новый issue
не повторил на Лин. попробую сегодня на Вин10

**Comment by Alexey-T** [comment]
@kvichans  решили уже?

**Comment by kvichans** [comment]
:) Видимо "да". Уже даже не вспомнить, как это повторить
