### ISSUE TITLE
Macros plugin stops working after 1-2 calls

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#17]
@MiroslavMatas @kvichans 
I move discusstion here
@kvichans can search all info in Cud wiki.
https://github.com/Alexey-T/CudaText/issues/2521

**Comment by kvichans** [comment]
> search all info in Cud wiki

Может быть в АПИ уже есть команда для разрыва хоткея и команды плагина - мне не удалось ее найти в вики. Что это за команда?

**Comment by Alexey-T** [comment]
кажется такого нет. есть для задания хоткея - dlg_hotkey(s).
дать такое api?

пока думаю что баг - в плагине

как разрыв команды может делать описанный баг? без удаления макро.

**Comment by kvichans** [comment]
Проверил! Модификая `keys.json` не вызывается на репро шагах.

**Comment by Alexey-T** [comment]
странно. тогда я неправ что тот кусок плохой. тогда не знаю в чем баг

в консоли вызываал dlg_hotkeys() с вашими 'cuda_marcos,......' и это писало хоткей в keys.json. когда давал хоткей прямо из вашего плага, оно НЕ писало хоткей в keys.json (в Лин хоткей в  CmdPalette не был виден сразу после задания в плаге)

плиз проверьте баг в Лин - хоткей сразу не работает?

**Comment by Alexey-T** [comment]
можете сделать мне зип с кудой чтобы я запустил макрос (не настраивая) и увидел баг?
