### ISSUE TITLE
Linux: dialog allows max val of "Times to run" is 1000

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#25]
слишком мало 1000.
надо 100 000
не нашел где вы для spinedit контрола ставите 1000, Куд тоже не ставит

**Comment by kvichans** [comment]
`tims_props  = '0,{},1'.format(self.dlg_prs.get('times',  1000))`

Поднять до 100 000?

**Comment by Alexey-T** [comment]
да, плиз

**Comment by kvichans** [comment]
Чуть глубже разобрался. Оказалось это настраивается
![image](https://user-images.githubusercontent.com/7419630/85193616-ebf80e00-b2d2-11ea-949d-bf62936df426.png)
`1000` - это умолчание. Его менять не вижу необходимости
