### ISSUE TITLE
Small problem with !MacroName

### ISSUE THREAD

**Issue by tmsg-gh** [kvichans/cuda_macros#26]
If I create a new macro, and enter an existing name (say "Macro1") in the name input box, I get a another input box asking again for the name. If, originally, I wanted to overwrite "Macro1" I now enter "!Macro1"... but now, a new macro called "!Macro1" is created rather than Macro1 being overwritten. I think the second input should support the same options as the first.

**Comment by Alexey-T** [comment]
Seems you show the main dialog, then select a macro, then press Rename.
there, you want to enter "!OldName".
yes, it is not supported at that place.
`!OldName` trick is supported only when dialog tells it in the text above.

seems @kvichans is not entusiast here, he had not time for this wish for years. closing.
