### ISSUE TITLE
Dlg not appears(bug)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#3]
Вызвал длг, 
повсавил ОТКЛ правого мемо
нажал start rec,
напечатал символы, вызывают длг---НЕ вызывается

теперь еще Custom кнопа не выз-ся.

**Comment by Alexey-T** [comment]
Command.dlg_config_custom:99 self.last_mcr_id, mcr_ind=(76768, 0)
Command.dlg_config_custom:101 mcr_ind=0

**Comment by kvichans** [comment]
cmd_MacroStop был?

**Comment by kvichans** [comment]
по шагам:
- из диалога StartRec
- что дальше набрали?
- каким способом пытались вызвать диалог?

**Comment by kvichans** [comment]
повторил

**Comment by Alexey-T** [comment]
- вызвал длг из Macros
- поставил ОТКЛ мемо2
- нажал startrec
- символы
- вызвал длг тамже---не вызывается
- рестарт-вызывается НО не раб кнопа custom

**Comment by kvichans** [comment]
custom - fix
не вызов - разбираюсь

**Comment by Alexey-T** [comment]
Длг симпатично. только зазор около run больш.
