### ISSUE TITLE
Menu needs "Stop/Cancel"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#5]
menu Macros 
1)has Start item ONLY if empty list. pls do not only
2)has NO stop/cancel at all.

OK to have 3 items. str/stop/can. in menu.

**Comment by kvichans** [comment]
посмотрю

**Comment by kvichans** [comment]
Может меню Макросы сделать ТОЛЬКО из четырех элементов?
- Вызов диалога
- ================
- Start rec
- Stop rec
- Cancel rec

**Comment by Alexey-T** [comment]
еще надо

Run macro >>
(sub)

**Comment by kvichans** [comment]
да, подменю это хорошо

**Comment by kvichans** [comment]
выложил

**Comment by Alexey-T** [comment]
Хорошо!
