### ISSUE TITLE
(poll) What is more?

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_macros#6]
Давайте собирать идеи. Что еще может улучшить Макросы
(1) Импорт/Экспорт

**Comment by kvichans** [comment]
(2) Безымянный(ые) макрос(ы). Для быстрого повторения текущих действий без мороки с именами

**Comment by Alexey-T** [comment]
(1)да, в файлы .cuda-macro - нужно
(2)не надо

**Comment by kvichans** [comment]
(2) "Безымянный макрос" - это две **новые** команды в плагине
- Начать запись _noname-macro_
- Вызвать _noname-macro_

**Comment by Alexey-T** [comment]
Думаю не надо это

**Comment by Alexey-T** [comment]
Син имеет "run till end'--не зн как там детектится "конец"---еще Нотепад++ имеет "run till end"

**Comment by kvichans** [comment]
"run till end" - это что?

**Comment by Alexey-T** [comment]
Запуск макро- можно указать Н раз, или "запуск до конца ф"

**Comment by kvichans** [comment]
(3) "До конца файла" - это как?

**Comment by kvichans** [comment]
(3) нет идей, как это реализовать

**Comment by kvichans** [comment]
(4) "Работать пока файл не перестанет изменяться". Вроде полезная опция. Только не понятно как отслеживать изменения от вызова к вызову. Для этого нужно какое-то API протянуть к undo-данным.

**Comment by kvichans** [comment]
(5) "Работать пока **размер** файла не перестанет изменяться". Это просто реализовать

**Comment by Alexey-T** [comment]
Нет- думаю макро 99% всегда меняет текст- полезно именно "дошли до посл. строки файла"

**Comment by kvichans** [comment]
Для (3)="до конца" у меня нет идей
Для (4)="пока есть изменения" можно через get_text_all(). Делать?

**Comment by kvichans** [comment]
(4) - Делаю, (5) - не делаю

**Comment by kvichans** [comment]
(4) Подскажите анг.фразу "Пока происходят изменения" для cap в check-контрол

**Comment by Alexey-T** [comment]
(4)Run while text changes
(3)ДоКонца же просто- если опц Run until end reached [x], то после команды в макр проверять- дошли до посл.строки(любой колонки)

**Comment by Alexey-T** [comment]
(3)не ОК для макров которые идут по одной строке долго(вправо)
ОК для которые идут "вниз"

**Comment by kvichans** [comment]
(3) Вы помните, что макросы имеют возможность делать поиски с wrap?

**Comment by kvichans** [comment]
(3) Можете дать критерий для проверки "дошел до конца"?

**Comment by Alexey-T** [comment]
Для пск-с-врап опция будет неприменима, для макро идущего вниз применима
Критерий-после команды ed.cmd мы на посл строке

**Comment by kvichans** [comment]
"мы на посл строке" - как проверять?

**Comment by Alexey-T** [comment]
первая каретка на послед. строке?

**Comment by kvichans** [comment]
Так и написать: "пока каретка не достигнет последней строки"?

**Comment by kvichans** [comment]
Сейчас уже есть кнопка Run и под ней
Times [1]
Wait [1] sec
[x] While text changes
Что еще дописать? 
[x] Till caret at end line

**Comment by Alexey-T** [comment]
Until caret on last line

**Comment by kvichans** [comment]
Выложил. Релизить так?

**Comment by Alexey-T** [comment]
stop record. задаю имя, и

```
  File "/home/user/.cudatext/py/cuda_macros/__init__.py", line 16, in on_macro
    def on_macro(self, ed_self, mcr_record):    return RLS.on_macro(ed_self, mcr_record)
  File "/home/user/.cudatext/py/cuda_macros/cd_macros.py", line 604, in on_macro
    ,'evl':self._record_data_to_cmds(mcr_record)
  File "/home/user/.cudatext/py/cuda_macros/cd_macros.py", line 811, in _record_data_to_cmds
    evls        = evls_c1.split(c1)
NameError: name 'c1' is not defined
```

**Comment by kvichans** [comment]
сори, был не прав при реформате

**Comment by kvichans** [comment]
выложил

**Comment by Alexey-T** [comment]
seconds deflt- лучше 3.

**Comment by kvichans** [comment]
это совсем не "лучше"

**Comment by Alexey-T** [comment]
Не раб.- макро делает

ed.cmd(cmds.cCommand_KeyEnd)
ed.cmd(cmds.cCommand_TextInsert,'---')
ed.cmd(cmds.cCommand_KeyDown)

ставлю число 10000, до конца. Не раб до конца

**Comment by kvichans** [comment]
см..

**Comment by kvichans** [comment]
fix
Будет ли лучше, если разрешить times=0, чтобы не ограничивать число повторов?

**Comment by kvichans** [comment]
Тогда и wait можно разрешить 0, чтобы не ограничивать по времени

**Comment by Alexey-T** [comment]
times/wait.Не надо

**Comment by Alexey-T** [comment]
fix -c1. а для неостановки?

**Comment by kvichans** [comment]
да, все fix и 0 для times,wait разрешил

**Comment by kvichans** [comment]
попробуйте

**Comment by Alexey-T** [comment]
0 times/wait не надо бы делать.

**Comment by kvichans** [comment]
хорошо, для wait верну мин 1

**Comment by Alexey-T** [comment]
Ок, и дефолт wait лучше 5
Раб-т

**Comment by kvichans** [comment]
ладно
