### ISSUE TITLE
Time of run 10sec

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_macros#8]
If time (play) >10sec, give warn "Macro plays too long (> 10 sec). Still continue?"
Time is option in Custom (10sec deft)

example: type "ab"/play 10000 times

**Comment by kvichans** [comment]
Для кого это?

**Comment by Alexey-T** [comment]
Виш для вас

**Comment by kvichans** [comment]
Дело хорошее, но подход не технологичный - так нужно будет делать в каждом методе каждого плагина.

**Comment by Alexey-T** [comment]
нет вовсе, только при play macro если лог на 10 т строк

**Comment by kvichans** [comment]
уже делаю для times

**Comment by Alexey-T** [comment]
Хор!

**Comment by kvichans** [comment]
Да, это хорошо
