### ISSUE TITLE
(poll) Optimization

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_macros#9]
Давайте вместе подумаем, какие оптимизации можно провести в списке вызовов у макроса
(1) Две вставки текста можно заменить на одну

```
ed.cmd(cmds.cCommand_TextInsert,'A')
ed.cmd(cmds.cCommand_TextInsert,'B')
```

на

```
ed.cmd(cmds.cCommand_TextInsert,'AB')
```

**Comment by Alexey-T** [comment]
(2)БЕЗ eval пускать. просто ed.cmd

**Comment by kvichans** [comment]
(2) Поясните. В чем идея? Есть тексты команд, а надо выполнять сами команды. Как?

**Comment by Alexey-T** [comment]
есть code, есть param. Делать ed.cmd(code, param)

**Comment by kvichans** [comment]
(2) Подумаю

**Comment by Alexey-T** [comment]
Не оч работает _ваша идея- 1000 запусков печати "аа" -не дает 1 запуск "аа"*1000

**Comment by Alexey-T** [comment]
(удалил)

**Comment by kvichans** [comment]
(2) Подумал. Не поможет. Уже сейчас весь макрос выполняется внутри **одного** exec.

**Comment by Alexey-T** [comment]
Ок..
